// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXnemlWa5RQ7bmDQA7OxSBHVQlxWUgi8',
    appId: '1:214593168407:web:45912aa3c5d5521b6f6852',
    messagingSenderId: '214593168407',
    projectId: 'lapar-app-anindita',
    authDomain: 'lapar-app-anindita.firebaseapp.com',
    storageBucket: 'lapar-app-anindita.firebasestorage.app',
    measurementId: 'G-9DQ04QH4WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAztIxx3CRjim75d-0feSz7MMEq1YAfKpY',
    appId: '1:214593168407:android:8b5afa6e20ada66d6f6852',
    messagingSenderId: '214593168407',
    projectId: 'lapar-app-anindita',
    storageBucket: 'lapar-app-anindita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJ4aOw8GVdzrhip-yCyNBVV36WBq1ruY',
    appId: '1:214593168407:ios:67ceb5f43b55b0f36f6852',
    messagingSenderId: '214593168407',
    projectId: 'lapar-app-anindita',
    storageBucket: 'lapar-app-anindita.firebasestorage.app',
    androidClientId: '214593168407-99644vroltmpifghqv883bbfh61lbdc0.apps.googleusercontent.com',
    iosClientId: '214593168407-m55mpof3tp2gcpoaoe0hv4o8npppii4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.undanganApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJ4aOw8GVdzrhip-yCyNBVV36WBq1ruY',
    appId: '1:214593168407:ios:67ceb5f43b55b0f36f6852',
    messagingSenderId: '214593168407',
    projectId: 'lapar-app-anindita',
    storageBucket: 'lapar-app-anindita.firebasestorage.app',
    androidClientId: '214593168407-99644vroltmpifghqv883bbfh61lbdc0.apps.googleusercontent.com',
    iosClientId: '214593168407-m55mpof3tp2gcpoaoe0hv4o8npppii4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.undanganApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVXnemlWa5RQ7bmDQA7OxSBHVQlxWUgi8',
    appId: '1:214593168407:web:96daf14ecc83c2936f6852',
    messagingSenderId: '214593168407',
    projectId: 'lapar-app-anindita',
    authDomain: 'lapar-app-anindita.firebaseapp.com',
    storageBucket: 'lapar-app-anindita.firebasestorage.app',
    measurementId: 'G-LJHXN7187L',
  );

}